stages: 
  - staging
  - staging-admin    
  - production

.deploy-base:
  rules:
    - when: manual 
  image: quay.io/dcole/controller-configuration:dev #<--could eventually create stage/tags and use $ENV instead of 'dev'
  script:
    - ansible-playbook -i localhost, controller-configuration.yml -e "env='$ENV' controller_username=$CONTROLLER_USERNAME controller_password=$CONTROLLER_PASSWORD controller_hostname=$CONTROLLER_URL controller_validate_certs=false" -vvv

staging-job:      # This job runs in staging environment.
  stage: staging  
  environment: 
    name: controller1 #<-these should probably be vars in gitlab -> $ENV or something else
    url: $CONTROLLER_URL_STAGING #<-these should probably be vars in gitlab -> $CONTROLLER_URL
  variables:
    ENV: "staging"
    CONTROLLER_URL: $CONTROLLER_URL_STAGING
    CONTROLLER_PASSWORD: $CONTROLLER_PASSWORD_STAGING
    CONTROLLER_USERNAME: $CONTROLLER_USERNAME_STAGING
  extends: .deploy-base

staging-admin-job:      # This job runs in the staging-admin environment.
  stage: staging-admin  
  environment: 
    name: controller2 #<-these should probably be vars in gitlab -> $ENV or something else
    url: $CONTROLLER_URL_STAGING_ADMIN #<-these should probably be vars in gitlab -> $CONTROLLER_URL
  variables:
    ENV: "staging-admin"
    CONTROLLER_URL: $CONTROLLER_URL_STAGING
    CONTROLLER_PASSWORD: $CONTROLLER_PASSWORD_STAGING_ADMIN
    CONTROLLER_USERNAME: $CONTROLLER_USERNAME_STAGING_ADMIN
  extends: .deploy-base

production-job:      # This job runs in the production stage.
  stage: production  
  environment: 
    name: controller3 #<-these should probably be vars in gitlab -> $ENV or something else
    url: $CONTROLLER_URL_PRODUCTION #<-these should probably be vars in gitlab -> $CONTROLLER_URL
  variables:
    ENV: "production"
    CONTROLLER_URL: $CONTROLLER_URL_PRODUCTION
    CONTROLLER_PASSWORD: $CONTROLLER_PASSWORD_PRODUCTION
    CONTROLLER_USERNAME: $CONTROLLER_USERNAME_PRODUCTION
  extends: .deploy-base
